#!/bin/bash

source llvm_patch.sh # imports function inline_patch_mir_file

# SET BY USER
OUR_LLVM_BINARIES=`realpath ~/llvm-project/build/bin`
CLANG="$OUR_LLVM_BINARIES/clang" # need the underlying clang driver that ciocc uses
LLC="$OUR_LLVM_BINARIES/llc"
LLVM_MC="$OUR_LLVM_BINARIES/llvm-mc"
CIOCC=`realpath ./ciocc`
CC="$CIOCC"
CHECKER_PLUGIN_PATH=`realpath ./checker/bap/interval/`

# cio defaults
TOOLNAME=cio
TIMESTAMP=$(TZ='America/Los_Angeles' date +%F-%T-%Z)
BUILD_DIR="./${TIMESTAMP}-${TOOLNAME}-build"
NUM_MAKE_JOB_SLOTS=8

EXTRA_CFLAGS=""
EXTRA_CHECKER_FLAGS=""

IS_LIBSODIUM=0

MITIGATE_SS=0
MITIGATE_CS=0
DO_SYMEX=1
DO_CLEAN=0

function usage
{
    echo "Usage: $TOOLNAME [ -h | --help (displays this message) ]
			   [ -c | --cc <path to c compiler> ]
    	 	 	   [ -p | --checker-plugin-path <path to dir with uarch_checker.plugin> ]
			   [ -o | --big-obj <path where $TOOLNAME puts jammed together obj file> ]
			   [ -b | --build-dir <path where $TOOLNAME stores intermeiate build artifacts> ]
			   [ -p | --cflags \"<~double quoted string~ of extra cflags for CC>\" ]
			   [ -e | --checker-flags \"<~double quoted string~ of extra flags for uarch_checker>\" ]
			   [ -j <num make job slots> ]
			   [ --is-libsodium <run libsodium init> ]
			   [ --ss (do silent store checks and mitigations) ]
			   [ --cs (do comp simp checks and mitigaitons) ]
			   [ --clean (clean up intermediate build artifacts from the dir specified by -t or --crypto-dir flags) ]
			   -f | --config-file <path to uarch checker config file for checking>
			   -t | --crypto-dir <path to the crypto lib project that has the root makefile>
			  
	       	 --config-file and crypto_project_dir_root are required arguments. If they are not passed,
                 the defaults of ${CC} and $(pwd) are used respectively."
    exit 1
}

PARSED_ARGS=$(getopt -o "hc:p:b:o:f:e:p:t:j:" -l "help,clean,cc:,checker-plugin-path:,build-dir:,big-obj:,config-file:,checker-flags:,cflags:,crypto-dir:,is-libsodium,ss,cs,nosymex" -n $TOOLNAME -- "$@")

if [[ $? -ne 0 ]]; then
       echo "Error parsing args"
       usage
fi

# echo $PARSED_ARGS

eval set -- "$PARSED_ARGS"
unset PARSED_ARGS

while true; do
    case "$1" in
	'-h' | '--help')
	    usage
	    ;;
	'-j')
	    NUM_MAKE_JOB_SLOTS=$2
	    shift 2
	    continue
	    ;;
	'--clean')
	    DO_CLEAN=1
	    shift
	    continue
	    ;;
	'--is-libsodium')
	    IS_LIBSODIUM=1
	    shift
	    continue
	    ;;
	'--ss')
	    MITIGATE_SS=1
	    shift
	    continue
	    ;;
	'--cs')
	    MITIGATE_CS=1
	    shift
	    continue
	    ;;
	'--nosymex')
	    DO_SYMEX=0
	    shift
	    continue
	    ;;
	'-c' | '--cc')
	    echo CC opt
	    CC=$2
	    shift 2
	    continue
	    ;;
	'-p' | '--checker-plugin-path')
	    CHECKER_PLUGIN_PATH=$2
	    shift 2
	    continue
	    ;;
	'-b' | '--build-dir')
	    BUILD_DIR=$2
	    shift 2
	    continue
	    ;;
	'-o' | '--big-obj')
	    BIG_OBJ=$2
	    shift 2
	    continue
	    ;;
	'-f' | '--config-file')
	    CONFIG_FILE=$2
	    shift 2
	    continue
	    ;;
	'-e' | '--checker-flags')
	    EXTRA_CHECKER_FLAGS=$2
	    shift 2
	    continue
	    ;;
	'-p' | '--cflags')
	    EXTRA_CFLAGS=$2
	    shift 2
	    continue
	    ;;
	'-t' | '--crypto-dir')
	    TARGET_DIR=$2
	    shift 2
	    continue
	    ;;
	'--')
	    shift
	    break
	    ;;
	*)
	    echo "Unknown option $1"
	    usage
	    ;;
    esac
    shift
done

BUILD_DIR=$(realpath "$BUILD_DIR")
mkdir "$BUILD_DIR"
NORMAL_MAKE_LOG="${BUILD_DIR}/normal.make.log"
BIG_OBJ="${BUILD_DIR}/jammed.together.o"
ALL_SECRETS_CSV="${BUILD_DIR}/secrets.csv"
BAP_LOGS="${BUILD_DIR}/bap.log"
CHECKER_ALERTS_CSV="${BUILD_DIR}/checker.alerts.csv"

if [[ "$DO_CLEAN" -eq 1 ]]; then
    if [[ -n "$TARGET_DIR" ]]; then
	set -x
	find "$TARGET_DIR" -iname '*.ciocc' -delete
	find "$TARGET_DIR" -iname '*.mir' -delete
	find "$TARGET_DIR" -iname '*.ll' -delete
	find "$TARGET_DIR" -iname '*.o' -delete
	find "$TARGET_DIR" -iname '*.secrets.csv' -delete
	find "$TARGET_DIR" -iname '*.mirbak' -delete
	# if [[ -n "$BUILD_DIR" && -d "$BUILD_DIR" ]]; then
	#     rm -r "$BUILD_DIR"
	# fi
	exit 0
    else
	echo "--crypto-dir or -t option must be specified when using --clean"
	exit 1
    fi
fi

# check if bap is installed for the checkers
HAS_BAP=$(which bap)
if [[ $? -ne 0 ]]; then
    echo Looks like bap is not installed or available on your path.
    echo To install bap:
    echo -e "\t1. Install the OCaml package manager, opam, using the system package manager, then run the following commands:"
    echo -e "\t2. opam switch create bap-alpha --repos default,bap=git+https://github.com/BinaryAnalysisPlatform/opam-repository#testing 4.11.2+flambda"
    echo -e "\t3. opam install bap"
    echo -e "\t4. opam install bap-primus-symbolic-executor"
    echo -e "\t5. opam install z3"
    echo -e '\t6. eval $(opam env)'
    exit 2
fi

if [[ "$DO_SYMEX" -eq 1 ]]; then
    CHECKER_SYMEX_FLAGS=""
else
    CHECKER_SYMEX_FLAGS="--uarch-checker-no-symex"
fi

if [[ "$MITIGATE_CS" -eq 0 ]]; then
    CHECKER_CS_FLAGS=""
    CC_CS_FLAGS=""
    LLC_CS_FLAGS=""
else
    CHECKER_CS_FLAGS="--uarch-checker-cs"
    CC_CS_FLAGS="-mllvm --x86-cs -mllvm --x86-cs-csv-path=${CHECKER_ALERTS_CSV}"
    LLC_CS_FLAGS="--x86-cs --x86-cs-csv-path=${CHECKER_ALERTS_CSV}"
fi

if [[ "$MITIGATE_SS" -eq 0 ]]; then
    CHECKER_SS_FLAGS=""
    CC_SS_FLAGS=""
    LLC_SS_FLAGS=""
else
    CHECKER_SS_FLAGS="--uarch-checker-ss"
    CC_SS_FLAGS="-mllvm --x86-ss -mllvm --x86-ss-csv-path=${CHECKER_ALERTS_CSV}"
    LLC_SS_FLAGS="--x86-ss --x86-ss-csv-path=${CHECKER_ALERTS_CSV}"
fi

# build checkers
echo "Building checkers..."
make checker
if [[ $? -ne 0 ]]; then
	echo Couldn\'t build checkers. Please fix the problem and try again
	exit 2
fi

# if target is libsodium, initialize and patch libsodium submodule
if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
    echo "Initializing libsodium submodule..."
    make libsodium_init
fi

# need to set cio to a known-good state, so clean, re-configure
make --directory=$TARGET_DIR clean

pushd .
# need the underlying clang driver that ciocc uses in configure.
# ciocc currently does not work here
if [[ -e "$TARGET_DIR/configure" ]]; then
    cd $TARGET_DIR; ./configure CC=$CLANG
    CONFIG_RES=$?
    popd

    if [[ $CONFIG_RES -ne 0 ]]; then
	echo "Error running ./configure in $TARGET_DIR. $TOOLNAME exiting."
	exit $CONFIG_RES
    fi
fi

# make the dir to hold all of the build artifacts
echo "Creating ${TOOLNAME} build dir ${BUILD_DIR}..."
if [[ -e $BUILD_DIR ]]; then
    echo it already exists, removing old build dir first...
    rm -r $BUILD_DIR
fi
mkdir $BUILD_DIR
echo done

echo "Running target's makefile: make -j 32 --directory=$TARGET_DIR CC=$CC"
make -j 32 --directory=$TARGET_DIR CC=$CC
COMPILE_PASS_RES=$?
# echo compile_pass_res is $COMPILE_PASS_RES
echo done

if [[ $COMPILE_PASS_RES -ne 0 ]]; then
    echo "Error running $TOOLNAME initial compilation pass. $TOOLNAME exiting."
    exit $COMPILE_PASS_RES
fi

# if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
#     echo 'init sodium_init' > $CONFIG_FILE
# fi



# # put all per-function secret csv contents into one big  csv file
# # echo "Gathering all per-function secret csv files into ${ALL_SECRETS_CSV}..."
# find $TARGET_DIR -name '*secrets.csv' -a ! -empty | xargs -I '{}' cat '{}' >> $CONFIG_FILE
# GATHER_SECRETS_RES=$?
# echo done

# if [[ $GATHER_SECRETS_RES -ne 0 ]]; then
#     echo "Error gathering all per-function secret csv files into one. $TOOLNAME exiting."
#     exit $GATHER_SECRETS_RES
# fi

echo "Cleaning up per-function secret csv files..."
find $TARGET_DIR -name '*secrets.csv' -a ! -path "*${BUILD_DIR}*" -delete
echo done

# put all the object files into one big object file
if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
    source $TARGET_DIR/src/libsodium/libsodium.la
    LIBNA_SHARED_LIB=$(find $TARGET_DIR -name "$dlname")
    BUILD_BIG_OBJ_RES=$?
    if [[ "$BUILD_BIG_OBJ_RES" -eq 0 ]]; then
	cp $LIBNA_SHARED_LIB $BIG_OBJ
    fi
else
    echo "Gathering all intermediate object files into ${BIG_OBJ}..."
    find $TARGET_DIR -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o $BIG_OBJ -lc
    BUILD_BIG_OBJ_RES=$?
    echo done
fi

if [[ $BUILD_BIG_OBJ_RES -ne 0 ]]; then
    echo "Error jamming all separate object files into one for use by checker. $TOOLNAME exiting."
    exit $BUILD_BIG_OBJ_RES
fi

echo "SHA256 of pre-mitigation $BIG_OBJ is:"
echo $(sha256sum $BIG_OBJ)

echo Dumping BIR and DKNOWLEDGE into $BUILD_DIR/jammed.together.dbir.txt
bap -dbir --no-optimization --bil-optimization=0 $BIG_OBJ &> $BUILD_DIR/jammed.together.dbir.txt
bap -dknowledge --no-optimization --bil-optimization=0 $BIG_OBJ >> $BUILD_DIR/jammed.together.dbir.txt 2>&1

echo "Starting checker on ${BIG_OBJ} using secrets file ${ALL_SECRETS_CSV}"
echo "Start time is: $(TZ='America/Los_Angeles' date +%F-%T-%Z)"
echo "logging to ${BAP_LOGS}"
bap \
    --plugin-path=$CHECKER_PLUGIN_PATH \
    --pass=uarch-checker \
    --no-optimization --bil-optimization=0 \
    --uarch-checker-output-csv-file=$CHECKER_ALERTS_CSV \
    $CHECKER_CS_FLAGS \
    $CHECKER_SS_FLAGS \
    $CHECKER_SYMEX_FLAGS \
    --uarch-checker-symex-profiling-output-file=./symex-profiling-data.csv \
    --uarch-checker-config-file=$CONFIG_FILE \
    $BIG_OBJ > $BAP_LOGS 2>&1
echo "Done checking $BIG_OBJ at $(TZ='America/Los_Angeles' date +%F-%T-%Z)"

echo "Checking if bap actually ran... you should also check that the elapsed time above is >= 10 minutes"
LINES_IN_BAP_ALERTS=$(wc -l "$CHECKER_ALERTS_CSV" | awk '{ print $1 }')
if [[ $LINES_IN_BAP_ALERTS -le 1 ]]; then
    # check for <= 1 because if it is empty or only contains the header row, there is probably a problem
    echo "ERROR: Number of rows in bap alerts file ($CHECKER_ALERTS_CSV) is <= 1 after checking step."
    echo "ERROR: BAP probably did not run or did not run properly. Please check ($BAP_LOGS) for more info"
    echo "ERROR: exiting."
    exit 3
fi

set -x

# make --directory="$TARGET_DIR" clean

ALL_MIR_FILES=$(find $TARGET_DIR -iname '*.mir' -a ! -iname '*.indexed.mir')
for MIR_FILE in $ALL_MIR_FILES; do
    CIOCC_COMPILATION_FILE=${MIR_FILE/%.mir/.ciocc}
    LIBTOOL_FILE=${MIR_FILE/%.mir/.lo}
    if [[ ! (-e "$CIOCC_COMPILATION_FILE") ]]; then
	echo "ciocc metadata file for MIR file $MIR_FILE doesn't exist"
	exit 3
    fi

    if [[ "$(basename $MIR_FILE)" == "librdrand_la-randombytes_internal_random.mir" ]]; then
	continue
    fi
    # this source provides definitions for ASM_FILE, MIR_FILE, OBJ_FILE,
    # LIBTOOL_OBJ_FILE
    source "$CIOCC_COMPILATION_FILE"
    source "$LIBTOOL_FILE"
    # echo "$LLC --relocation-model=pic $LLC_SS_FLAGS $LLC_CS_FLAGS $MIR_FILE -o $ASM_FILE"
    # $LLC -x=mir --relocation-model=pic $LLC_SS_FLAGS $LLC_CS_FLAGS $MIR_FILE -o $ASM_FILE
    LLC_PASSES=""
    MITIGATION_OPTIONS=""
    if [[ "$MITIGATE_SS" -eq 1 ]]; then
	LLC_PASSES="ss"
	MITIGATION_OPTIONS="$MITIGATION_OPTIONS --x86-ss --x86-ss-csv-path=$CHECKER_ALERTS_CSV"
    fi
    if [[ "$MITIGATE_CS" -eq 1 ]]; then
	LLC_PASSES="$LLC_PASSES,csimp-mitigation"
	MITIGATION_OPTIONS="$MITIGATION_OPTIONS --x86-cs --x86-cs-csv-path=$CHECKER_ALERTS_CSV"
    fi
    
    inline_patch_mir_file "$MIR_FILE"

    # --debug-pass=Structure
    $LLC --disable-verify \
	 -x=mir \
	 --relocation-model=pic \
	 --run-pass="$LLC_PASSES" $MITIGATION_OPTIONS \
	 "$MIR_FILE" -o "$MIR_FILE.mitigated"

    MITIGATION_PASS_RESULT=$?

    if [[ $MITIGATION_PASS_RESULT -eq 0 ]]; then
	mv "$MIR_FILE.mitigated" "$MIR_FILE"

	inline_patch_mir_file "$MIR_FILE"
	
	# $LLC --disable-verify \
	#      --debug-pass=Structure \
	#      -x=mir \
	#      --relocation-model=pic \
	#      --start-after=csimp-mitigation \
	#      "$MIR_FILE" -o "$ASM_FILE"
	
	# TO_ASM_RESULT=$?

	# if [[ $TO_ASM_RESULT -ne 0 ]]; then
	#     echo "Error compiling MIR to ASM: $MIR_FILE -> $ASM_FILE"
	#     # exit $TO_ASM_RESULT
	# fi

	TO_ASM_RESULT=0
	if [[ $TO_ASM_RESULT -eq 0 ]]; then
	    # $LLVM_MC --position-independent "$ASM_FILE" --filetype=obj -o "$OBJ_FILE"
	    $LLC --disable-verify \
		 --debug-pass=Structure \
		 -x=mir \
		 --start-after=csimp-mitigation \
		 --relocation-model=pic \
		 --filetype=obj \
		 "$MIR_FILE" -o "$OBJ_FILE"

	    TO_OBJ_RESULT=$?
	    if [[ $TO_OBJ_RESULT -ne 0 ]]; then
		echo "Error compiling mitigated hardened assembly to object file for $MIR_FILE -> $ASM_FILE -> $OBJ_FILE"
		# exit $TO_OBJ_RESULT
	    fi
	fi

	# echo "$LLVM_MC --position-independent $ASM_FILE -filetype=obj -o $OBJ_FILE"
	# $LLVM_MC --position-independent "$ASM_FILE" --filetype=obj -o "$OBJ_FILE"
	# echo "cp $OBJECT_FILE $OBJECT_FILE/../$pic_object"
	BASE_DIR=$(dirname "$OBJ_FILE")
	cp "$OBJ_FILE" "$BASE_DIR/$pic_object"
	cp "$OBJ_FILE" "$BASE_DIR/$non_pic_object"
	touch "$LIBTOOL_OBJ_FILE"
    else
	echo "Error running mitigation passes '--run-pass=$LLC_PASSES' on $MIR_FILE"
    fi
done

# after regenerating the object files, the shared libraries should be out of
# date, so running make should regenerate these automagically
# don't need to use ciocc here
make --directory="$TARGET_DIR" CC="$CLANG" -j "$NUM_MAKE_JOB_SLOTS"

RELINK_RES=$?

if [[ $RELINK_RES -ne 0 ]]; then
    echo "Error relinking all object togethers after mitigation pass: $RELINK_RES"
    exit $RELINK_RES
fi

# put all the object files into one big object file again
if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
    source "$TARGET_DIR/src/libsodium/libsodium.la"
    LIBNA_SHARED_LIB=$(find "$TARGET_DIR" -name "$dlname")
    BUILD_BIG_OBJ_RES=$?
    if [[ "$BUILD_BIG_OBJ_RES" -eq 0 ]]; then
	cp "$LIBNA_SHARED_LIB" "$BIG_OBJ.verification.o"
    fi
else
    echo "Gathering all intermediate object files into ${BIG_OBJ}..."
    find "$TARGET_DIR" -name '*.o' -a ! -path '*.libs*' | xargs ld -O0 -o "$BIG_OBJ.verification.o" -lc
    BUILD_BIG_OBJ_RES=$?
    echo done
fi

if [[ "$BUILD_BIG_OBJ_RES" -ne 0 ]]; then
    echo "Error jamming all separate object files into one for use by checker. $TOOLNAME exiting."
    exit $BUILD_BIG_OBJ_RES
fi

echo "SHA256 of post-mitigation $BIG_OBJ.verification.o is:"
echo $(sha256sum "$BIG_OBJ.verification.o")

echo Running verification pass...
echo "Start time is: $(TZ='America/Los_Angeles' date +%F-%T-%Z)"
echo "logging to ${BAP_LOGS}"
bap \
    --plugin-path=$CHECKER_PLUGIN_PATH \
    --pass=uarch-checker \
    --no-optimization --bil-optimization=0 \
    --uarch-checker-output-csv-file=${CHECKER_ALERTS_CSV}.verification.csv \
    $CHECKER_CS_FLAGS \
    $CHECKER_SS_FLAGS \
    $CHECKER_SYMEX_FLAGS \
    --uarch-checker-symex-profiling-output-file=./symex-profiling-data.csv \
    --uarch-checker-config-file=$CONFIG_FILE \
    ${BIG_OBJ}.verification.o > ${BAP_LOGS}.verification.log 2>&1
echo "Done checking $BIG_OBJ at $(TZ='America/Los_Angeles' date +%F-%T-%Z)"
echo done

if [[ "$IS_LIBSODIUM" -eq 1 ]]; then
    echo "Running libsodium unit tests..."
    make -j 32 --directory="$TARGET_DIR" check
    echo done
fi

LINES_IN_BAP_VERIF_ALERTS=$(wc -l "${CHECKER_ALERTS_CSV}.verification.csv" | awk '{ print $1 }')
if [[ $LINES_IN_BAP_VERIF_ALERTS -gt 1 ]]; then
    echo "ERROR: BAP and checkers couldn't verify that the final code is free of leaks"
    echo "ERROR: See ${CHECKER_ALERTS_CSV}.verification.csv and ${BAP_LOGS}.verification.log for more info"
    echo "ERROR: exiting"
    exit 4
else
    exit 0
fi
