#!/bin/bash

TOOLNAME=ciocc
INIT_ARGS="$@"

SEEN_C_FLAG=0
SEEN_O_FLAG=0
OPT_FLAG="" # llc defaults to O2

C_FILE=""
OBJ_FILE=""
ASM_FILE=""
LL_FILE=""
MIR_FILE=""
LL_FILE=""

# for saving state about this object file's compilation for later cio use.
# cio calls make which calls libtool which calls ciocc.
# a lot of cio's work runs on intermediate libtool build artifacts.
# ciocc knows about these build artifacts, but cio does not.
# so save some of this info in a bash script denoted by $CIOCC_FILE
# that cio can source--i.e., 'source $CIOCC_FILE' where
# CIOCC_FILE is the mir file name for this object file
# with the .mir suffix changed to .ciocc--i.e., source ${SOME_MIR_FILE/%.mir/.ciocc}
# gives cio the needed information for this .mir/.o/.ll file.
CIOCC_FILE="" 

COMPILER_DIR="/home/mkf/llvm-project/build/bin/"
COMPILER="$COMPILER_DIR/clang"
LLC="$COMPILER_DIR/llc"
LLVM_MC="$COMPILER_DIR/llvm-mc"

LLC_FLAGS=""
LLVM_MC_FLAGS=""

FINAL_ARGS=()

while [[ $# -gt 0 ]]; do
    if [[ ! ("$1" =~ 'PACKAGE_STRING') ]]; then
	FINAL_ARGS+=( "$1" )
    fi
    
    case "$1" in
	'-fPIC')
	    LLC_FLAGS="--relocation-model=pic"
	    LLVM_MC_FLAGS="--position-independent"
	    shift
	    continue
	    ;;
	'-o')
	    SEEN_O_FLAG=1
	    OBJ_FILE="$2"
	    LL_FILE=${OBJ_FILE/%.o/.ll}
	    LL_FILE=${LL_FILE/%.lo/.ll}
	    MIR_FILE=${OBJ_FILE/%.o/.mir}
	    MIR_FILE=${MIR_FILE/%.lo/.mir}
	    ASM_FILE=${OBJ_FILE/%.o/.s}
	    ASM_FILE=${ASM_FILE/%.lo/.s}
	    CIOCC_FILE=${MIR_FILE/%.mir/.ciocc}

	    # libtool/autotools used?
	    LL_FILE=${LL_FILE/.libs/}
	    MIR_FILE=${MIR_FILE/.libs/}
	    ASM_FILE=${ASM_FILE/.libs/}
	    CIOCC_FILE=${CIOCC_FILE/.libs/}
	    
	    # if [[ "$OBJ_FILE" =~ '\.libs' ]]; then
	    # 	echo "has .libs"
	    # 	LL_FILE=${LL_FILE/.libs/}
	    # 	MIR_FILE=${MIR_FILE/.libs/}
	    # 	ASM_FILE=${ASM_FILE/.libs/}
	    # else
	    # 	echo "doesn't have .libs"
	    # fi
	    FINAL_ARGS+=( "$LL_FILE" )
	    shift 2
	    continue
	    ;;
	'-c')
	    if [[ "$2" =~ \.(c|cpp)$ ]]; then
		SEEN_C_FLAG=1
		C_FILE="$2"
		FINAL_ARGS+=( "$2" )
		shift 2
	    else
		shift
	    fi
	    continue
	    ;;
	'-O0' | '-O1' | '-O2' | '-O3' | '-Ofast')
	    OPT_FLAG=$1
	    FINAL_ARGS+=( "-emit-llvm" )
	    shift
	    continue
	    ;;
	*)
	    shift
	    continue
	    ;;
    esac
    shift
done

# if '$(CC) ... -c foo.c -o foo.o ...' command, then
# run things through '.c -> .ll -> .mir -> .o' pipeline (or comparable)
if [[ "$SEEN_C_FLAG" -eq 1 && "$SEEN_O_FLAG" -eq 1 ]]; then
    if [[ -z "$LL_FILE" || -z "$OBJ_FILE" || -z "$MIR_FILE" ]]; then
	echo "Error getting .ll/.mir file name for command: $@, OBJ_FILE=$OBJ_FILE"
	exit 1
    fi
    
    # Make doesn't properly handle our intermediate build artifacts
    # Build them clean from scratch every time
    test -e "$LL_FILE" && rm "$LL_FILE"
    test -e "$MIR_FILE" && rm "$MIR_FILE"
    test -e "$ASM_FILE" && rm "$ASM_FILE"

    echo "$COMPILER ${FINAL_ARGS[@]}"
    $COMPILER "${FINAL_ARGS[@]}"
    echo "$LLC $LLC_FLAGS $OPT_FLAG $LL_FILE -o $MIR_FILE"
    $LLC "$LLC_FLAGS" $OPT_FLAG $LL_FILE -o $MIR_FILE >/dev/null
    echo "$LLC $LLC_FLAGS $OPT_FLAG $LL_FILE -o $ASM_FILE"
    $LLC "$LLC_FLAGS" $OPT_FLAG $LL_FILE -o $ASM_FILE >/dev/null

    echo "$LLVM_MC $LLVM_MC_FLAGS $ASM_FILE -filetype=obj -o $OBJ_FILE"
    $LLVM_MC "$LLVM_MC_FLAGS" $ASM_FILE -filetype=obj -o $OBJ_FILE

    echo "OBJ_FILE=$OBJ_FILE" >> "$CIOCC_FILE"
    echo "MIR_FILE=$MIR_FILE" >> "$CIOCC_FILE"
    echo "ASM_FILE=$ASM_FILE" >> "$CIOCC_FILE"
else
    # then probably linking or assembling, just pass the arguments through
    echo "$COMPILER $@"
    $COMPILER "$@"
fi

exit 0
