#!/bin/bash

# SET BY USER
OUR_CC=~/llvm-project/build/bin/clang
CHECKER_PLUGIN_PATH=~/checker/bap/interval/

BAP="bap --plugin-path=$CHECKER_PLUGIN_PATH --pass=uarch-checker --no-optimization --bil-optimization=0"
CIOCC_BUILD_DIR=./ciocc-build
CIOCC_NORMAL_MAKE_LOG=$CIOCC_BUILD_DIR/normal.make.log
BIG_OBJ=$CIOCC_BUILD_DIR/jammed.together.o

make clean

./configure CC=$OUR_CC

mkdir $CIOCC_BUILD_DIR

make --dry-run > $CIOCC_NORMAL_MAKE_LOG 2>&1

make CC=$OUR_CC

find . -name '*.o' -a ! -path '*.libs*' | xargs ld -z muldefs -o $BIG_OBJ -lc

$BAP $BIG_OBJ

make clean

make CC=$OUR_CC
